from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy_dev_utils.types.datetime import UTCDateTime


revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None

FILE_PURPOSE_ENUM = postgresql.ENUM(
    "ARTICLE_CONTENT_IMAGE",
    "ARTICLE_COVER_IMAGE",
    "ATTACHMENT",
    name="file_purpose_enum",
    create_type=False,
)
ARTICLE_FILE_USAGE_ARTICLE_FK = "articles_file_usage_article_id_fkey"
ARTICLE_FILE_USAGE_FILE_FK = "articles_file_usage_file_id_fkey"
ARTICLE_COVER_IMAGE_FILE_FK = "articles_article_cover_image_file_id_fkey"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    FILE_PURPOSE_ENUM.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "files__file_model",
        sa.Column(
            "purpose",
            FILE_PURPOSE_ENUM,
            nullable=False,
        ),
        sa.Column("namespace", sa.String(length=63), nullable=False),
        sa.Column("relative_path", sa.String(length=2048), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.func.replace(
                sa.cast(sa.func.gen_random_uuid(), sa.String()),
                "-",
                "",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            UTCDateTime(timezone=True),
            server_default=sa.func.timezone("utc", sa.func.current_timestamp()),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            UTCDateTime(timezone=True),
            server_default=sa.func.timezone("utc", sa.func.current_timestamp()),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "namespace", "relative_path", name="files_file_namespace_relative_path_uniq"
        ),
    )
    op.create_index(
        "files_file_purpose_created_id_idx",
        "files__file_model",
        ["purpose", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "articles__article_file_usage_model",
        sa.Column("article_id", sa.String(length=32), nullable=False),
        sa.Column("file_id", sa.String(length=32), nullable=False),
        sa.Column(
            "usage",
            FILE_PURPOSE_ENUM,
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.func.replace(
                sa.cast(sa.func.gen_random_uuid(), sa.String()),
                "-",
                "",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles__article_model.id"],
            name=ARTICLE_FILE_USAGE_ARTICLE_FK,
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files__file_model.id"],
            name=ARTICLE_FILE_USAGE_FILE_FK,
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "article_id", "file_id", "usage", name="articles_file_usage_article_file_usage_uniq"
        ),
    )
    op.create_index(
        "articles_file_usage_file_idx",
        "articles__article_file_usage_model",
        ["file_id"],
        unique=False,
    )
    op.add_column(
        "articles__article_model",
        sa.Column("cover_image_file_id", sa.String(length=32), nullable=True),
    )
    op.create_index(
        "articles_article_cover_image_file_idx",
        "articles__article_model",
        ["cover_image_file_id"],
        unique=False,
    )
    op.create_foreign_key(
        ARTICLE_COVER_IMAGE_FILE_FK,
        "articles__article_model",
        "files__file_model",
        ["cover_image_file_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("articles__article_model", "cover_image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles__article_model",
        sa.Column("cover_image_url", sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    )
    op.drop_constraint(ARTICLE_COVER_IMAGE_FILE_FK, "articles__article_model", type_="foreignkey")
    op.drop_index("articles_article_cover_image_file_idx", table_name="articles__article_model")
    op.drop_column("articles__article_model", "cover_image_file_id")
    op.drop_index("articles_file_usage_file_idx", table_name="articles__article_file_usage_model")
    op.drop_table("articles__article_file_usage_model")
    op.drop_index("files_file_purpose_created_id_idx", table_name="files__file_model")
    op.drop_table("files__file_model")
    FILE_PURPOSE_ENUM.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
