from alembic import op
import sqlalchemy as sa
from sqlalchemy_dev_utils.types.datetime import UTCDateTime


revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth__auth_session_model",
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "expires_at",
            UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["username"], ["auth__user_model.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("secret_hash", name="auth_sessions_secret_hash_uniq"),
    )
    op.create_index(
        "auth_sessions_expiry_idx", "auth__auth_session_model", ["expires_at"], unique=False
    )
    op.create_index(
        "auth_sessions_username_lower_active_expiry_idx",
        "auth__auth_session_model",
        [sa.literal_column("lower(username)").label("username_lower"), "is_revoked", "expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "auth_sessions_username_lower_active_expiry_idx", table_name="auth__auth_session_model"
    )
    op.drop_index("auth_sessions_expiry_idx", table_name="auth__auth_session_model")
    op.drop_table("auth__auth_session_model")
    # ### end Alembic commands ###
