from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy_dev_utils.types.datetime import UTCDateTime


revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None

AUTH_METHOD_ENUM = postgresql.ENUM(
    "PASSWORD",
    name="auth_session_auth_method_enum",
    create_type=False,
)
DEVICE_TYPE_ENUM = postgresql.ENUM(
    "DESKTOP",
    "MOBILE",
    "TABLET",
    "BOT",
    "UNKNOWN",
    name="auth_session_device_type_enum",
    create_type=False,
)
AUTH_SESSIONS = sa.table("auth__auth_session_model", sa.column("id", sa.String()))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute(sa.delete(AUTH_SESSIONS))
    AUTH_METHOD_ENUM.create(connection, checkfirst=True)
    DEVICE_TYPE_ENUM.create(connection, checkfirst=True)
    op.add_column(
        "auth__auth_session_model",
        sa.Column(
            "last_used_at",
            UTCDateTime(timezone=True),
            nullable=False,
        ),
    )
    op.add_column(
        "auth__auth_session_model",
        sa.Column("auth_method", AUTH_METHOD_ENUM, nullable=False),
    )
    op.add_column(
        "auth__auth_session_model",
        sa.Column("user_agent_display", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "auth__auth_session_model",
        sa.Column("user_agent_browser", sa.String(length=63), nullable=False),
    )
    op.add_column(
        "auth__auth_session_model", sa.Column("user_agent_os", sa.String(length=63), nullable=False)
    )
    op.add_column(
        "auth__auth_session_model",
        sa.Column("user_agent_device", DEVICE_TYPE_ENUM, nullable=False),
    )
    op.create_index(
        "auth_sessions_username_lower_active_last_used_idx",
        "auth__auth_session_model",
        [
            sa.literal_column("lower(username)").label("username_lower"),
            "is_revoked",
            "expires_at",
            sa.literal_column("last_used_at DESC"),
            "id",
        ],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "auth_sessions_username_lower_active_last_used_idx", table_name="auth__auth_session_model"
    )
    op.drop_column("auth__auth_session_model", "user_agent_device")
    op.drop_column("auth__auth_session_model", "user_agent_os")
    op.drop_column("auth__auth_session_model", "user_agent_browser")
    op.drop_column("auth__auth_session_model", "user_agent_display")
    op.drop_column("auth__auth_session_model", "auth_method")
    op.drop_column("auth__auth_session_model", "last_used_at")
    DEVICE_TYPE_ENUM.drop(op.get_bind(), checkfirst=True)
    AUTH_METHOD_ENUM.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
