from alembic import op
import sqlalchemy as sa
from sqlalchemy_dev_utils.types.datetime import UTCDateTime

from infra.config.settings import settings


revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None

AUTH_SESSIONS = sa.table(
    "auth__auth_session_model",
    sa.column("created_at", UTCDateTime(timezone=True)),
    sa.column("absolute_expires_at", UTCDateTime(timezone=True)),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth__auth_session_model",
        sa.Column(
            "absolute_expires_at",
            UTCDateTime(timezone=True),
            nullable=True,
        ),
    )
    op.get_bind().execute(
        sa.update(AUTH_SESSIONS).values(
            absolute_expires_at=AUTH_SESSIONS.c.created_at
            + sa.func.make_interval(
                0,
                0,
                0,
                0,
                0,
                0,
                settings.auth.session_absolute_expire_seconds,
            ),
        ),
    )
    op.alter_column(
        "auth__auth_session_model",
        "absolute_expires_at",
        existing_type=UTCDateTime(timezone=True),
        nullable=False,
    )
    op.drop_index(
        op.f("auth_sessions_username_lower_active_expiry_idx"),
        table_name="auth__auth_session_model",
    )
    op.create_index(
        "auth_sessions_username_lower_active_expiry_idx",
        "auth__auth_session_model",
        [
            sa.literal_column("lower(username)").label("username_lower"),
            "is_revoked",
            "expires_at",
            "absolute_expires_at",
        ],
        unique=False,
    )
    op.drop_index(
        op.f("auth_sessions_username_lower_active_last_used_idx"),
        table_name="auth__auth_session_model",
    )
    op.create_index(
        "auth_sessions_username_lower_active_last_used_idx",
        "auth__auth_session_model",
        [
            sa.literal_column("lower(username)").label("username_lower"),
            "is_revoked",
            "expires_at",
            "absolute_expires_at",
            sa.literal_column("last_used_at DESC"),
            "id",
        ],
        unique=False,
    )
    op.create_index(
        "auth_sessions_absolute_expiry_idx",
        "auth__auth_session_model",
        ["absolute_expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("auth_sessions_absolute_expiry_idx", table_name="auth__auth_session_model")
    op.drop_index(
        "auth_sessions_username_lower_active_last_used_idx", table_name="auth__auth_session_model"
    )
    op.create_index(
        op.f("auth_sessions_username_lower_active_last_used_idx"),
        "auth__auth_session_model",
        [
            sa.literal_column("lower(username)").label("username_lower"),
            "is_revoked",
            "expires_at",
            sa.literal_column("last_used_at DESC"),
            "id",
        ],
        unique=False,
    )
    op.drop_index(
        "auth_sessions_username_lower_active_expiry_idx", table_name="auth__auth_session_model"
    )
    op.create_index(
        op.f("auth_sessions_username_lower_active_expiry_idx"),
        "auth__auth_session_model",
        [sa.literal_column("lower(username)").label("username_lower"), "is_revoked", "expires_at"],
        unique=False,
    )
    op.drop_column("auth__auth_session_model", "absolute_expires_at")
    # ### end Alembic commands ###
