from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0019"
down_revision = "0018"
branch_labels = None
depends_on = None

ROLE_ENUM = postgresql.ENUM(
    "ANON",
    "USER",
    "MODERATOR",
    "ADMIN",
    "OWNER",
    name="role_enum",
    create_type=False,
)
AUTH_METHOD_ENUM = postgresql.ENUM(
    "PASSWORD",
    name="auth_session_auth_method_enum",
    create_type=False,
)
DEVICE_TYPE_ENUM = postgresql.ENUM(
    "DESKTOP",
    "MOBILE",
    "TABLET",
    "BOT",
    "UNKNOWN",
    name="auth_session_device_type_enum",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("auth_sessions_absolute_expiry_idx"), table_name="auth__auth_session_model")
    op.drop_index(op.f("auth_sessions_expiry_idx"), table_name="auth__auth_session_model")
    op.drop_index(
        op.f("auth_sessions_username_lower_active_expiry_idx"),
        table_name="auth__auth_session_model",
    )
    op.drop_index(
        op.f("auth_sessions_username_lower_active_last_used_idx"),
        table_name="auth__auth_session_model",
    )
    op.drop_table("auth__auth_session_model")
    op.drop_index(op.f("users_managed_accounts_list_idx"), table_name="auth__user_model")
    op.drop_index(
        op.f("users_single_owner_uniq"),
        table_name="auth__user_model",
        postgresql_where="(role = 'OWNER'::role_enum)",
    )
    op.drop_index(op.f("users_username_idx"), table_name="auth__user_model")
    op.drop_index(op.f("users_username_lower_uniq"), table_name="auth__user_model")
    op.drop_table("auth__user_model")
    DEVICE_TYPE_ENUM.drop(op.get_bind(), checkfirst=True)
    AUTH_METHOD_ENUM.drop(op.get_bind(), checkfirst=True)
    ROLE_ENUM.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ROLE_ENUM.create(op.get_bind(), checkfirst=True)
    AUTH_METHOD_ENUM.create(op.get_bind(), checkfirst=True)
    DEVICE_TYPE_ENUM.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "auth__user_model",
        sa.Column("username", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("password_hash", sa.VARCHAR(length=127), autoincrement=False, nullable=False),
        sa.Column(
            "role",
            ROLE_ENUM,
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("username", name=op.f("auth__user_model_pkey")),
    )
    op.create_index(
        op.f("users_username_lower_uniq"),
        "auth__user_model",
        [sa.literal_column("lower(username::text)")],
        unique=True,
    )
    op.create_index(op.f("users_username_idx"), "auth__user_model", ["username"], unique=False)
    op.create_index(
        op.f("users_single_owner_uniq"),
        "auth__user_model",
        ["role"],
        unique=True,
        postgresql_where="(role = 'OWNER'::role_enum)",
    )
    op.create_index(
        op.f("users_managed_accounts_list_idx"),
        "auth__user_model",
        ["role", sa.literal_column("lower(username::text)"), "username"],
        unique=False,
    )
    op.create_table(
        "auth__auth_session_model",
        sa.Column("username", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("secret_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("is_revoked", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            sa.VARCHAR(length=32),
            server_default=sa.text(
                "replace(((gen_random_uuid())::character varying)::text, '-'::text, ''::text)"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_used_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "auth_method",
            AUTH_METHOD_ENUM,
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_agent_display", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("user_agent_browser", sa.VARCHAR(length=63), autoincrement=False, nullable=False),
        sa.Column("user_agent_os", sa.VARCHAR(length=63), autoincrement=False, nullable=False),
        sa.Column(
            "user_agent_device",
            DEVICE_TYPE_ENUM,
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "absolute_expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["username"],
            ["auth__user_model.username"],
            name=op.f("auth__auth_session_model_username_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("auth__auth_session_model_pkey")),
        sa.UniqueConstraint(
            "secret_hash",
            name=op.f("auth_sessions_secret_hash_uniq"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("auth_sessions_username_lower_active_last_used_idx"),
        "auth__auth_session_model",
        [
            sa.literal_column("lower(username::text)"),
            "is_revoked",
            "expires_at",
            "absolute_expires_at",
            sa.literal_column("last_used_at DESC"),
            "id",
        ],
        unique=False,
    )
    op.create_index(
        op.f("auth_sessions_username_lower_active_expiry_idx"),
        "auth__auth_session_model",
        [
            sa.literal_column("lower(username::text)"),
            "is_revoked",
            "expires_at",
            "absolute_expires_at",
        ],
        unique=False,
    )
    op.create_index(
        op.f("auth_sessions_expiry_idx"), "auth__auth_session_model", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("auth_sessions_absolute_expiry_idx"),
        "auth__auth_session_model",
        ["absolute_expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###
